### ISSUE TITLE
[Fix Suggestions] Address Street Name Check

### ISSUE THREAD

**Issue by sayas01** [osmlab/atlas-checks#409] opened 2020-11-03 19:41 UTC
**Which Atlas check is the fix suggestion related to?** 

**AddressStreetNameCheck:**
Description:https://github.com/osmlab/atlas-checks/blob/dev/docs/checks/addressStreetNameCheck.md

Source Code: https://github.com/osmlab/atlas-checks/blob/dev/src/main/java/org/openstreetmap/atlas/checks/validation/points/AddressStreetNameCheck.java

**Describe more details of suggested fix(es)**

*Suggested Fix 1*: 

- Type: Tag

- Operation: Modify

- Action: Update the `addr:street` tag value of the point to the value of Name tag of adjacent edge. 

**Is there any code enhancement needed if adding the fix suggestion component?**

Yes, the AutoFix suggestion should be added only in the case where the total number of edges with Name tag within the given bounds is 1 and not for all flags.

If yes, provide details about what and where the enhancement is needed.  Ex. the fix requires excluding checks on relation

**Comment by vladlemberg** [comment] 2021-03-02 18:57
@sayas01, please assign it to me. thanks!

**Comment by vladlemberg** [comment] 2021-03-03 23:23
@sayas01, @Bentleysb, @atiannicelli,
I tested AddressStreetNameCheck output against US Metro Areas. Here is my observation: vast majority of flags are POIs locating in large plazas or shopping centers with physical addresses beyond default radius of 100m. The second group of flags are Address Points inside large apartment complexes. All of them most likely are FPs.  

Per our discussion with @Bentleysb, the Check is not ready for AutoFix and need additional tuning. Based on my observation, it should be some logical tuning instead of increasing radius distance. 

For example: Road Name Normalization. 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/62575608/109885542-83b84500-7c33-11eb-8ed0-2db7de9f0867.png">

I've created MR challenges with different radius: 100, 500, 1000 meters that can be passed for further investigation. 
https://maproulette.org/admin/project/43124

@sayas01, @Bentleysb, please advise the next step. Do we need to pass validation to your QA team ?

**Comment by Bentleysb** [comment] 2021-03-04 17:51
@vladlemberg, what percentage of the false positives you observed would you say fall under the road name normalization use case? I think part of the original impetus for this check was to flag these spelling and capitalization discrepancies, as they can cause problems for routing engines. 
I know there was also one use case you shared with me where the false positive was caused by the search distance. Are there any other general trends you have found in the false positives?

**Comment by vladlemberg** [comment] 2021-03-04 18:29
@Bentleysb, quite a lot. Please take a look at 1000m [challenge](https://maproulette.org/admin/project/43124).

typical example: Cortland Ave VS Cortland Avenue.
<img width="564" alt="image" src="https://user-images.githubusercontent.com/62575608/110011305-20caba80-7cd4-11eb-939e-b448e6dedbd7.png">

**Comment by vladlemberg** [comment] 2021-03-04 18:43
FP summary:
POIs, Address Points - can be fixes by increasing radius for example 1000m. however its not solving this issue completely.
Road Name - can be fixed by RoadName Standardization library where: N North St = North North Street. 
I have an experience of writing OSM Road Name standardization for other projects. Maybe we should do it for OSM Lab.

**Comment by Bentleysb** [comment] 2021-03-04 19:03
We can use a standardization library, but I would argue that we do not want to do that in this case. Based on the guidelines in the OSM wiki for both the [name tag](https://wiki.openstreetmap.org/wiki/Names#Notes) and [addr:street tag](https://wiki.openstreetmap.org/wiki/Key:addr) the street names should be standardized in the data. So I would say these are in fact true positive flags that should be fixed by standardizing the name tag and/or address tag. 
One way a standardization library could be used is to better identify these cases and give clearer instructions and possibly fix suggestions for the standardizations.

**Comment by vladlemberg** [comment] 2021-03-04 19:25
Agree, but in this case we end up of fixing Prefixes, Suffixes, Abbreviations and local highway names. its huge and in my understanding is totally different project or separate check.

**Comment by Bentleysb** [comment] 2021-03-08 19:51
I am not sure it is so different, but I think you're right. Perhaps it is better to create a new check to handle road name standardization, and try to exclude those cases from this check.

**Comment by vladlemberg** [comment] 2021-03-08 20:14
as far as I know every company processing OSM data have their own name normalizer. therefore the impact of fixing "Main St" to "Main Street" is rather low. however, I think implementing such library for atlas-checks will benefit the project. 

please advice what would be the next step for this task ?

**Comment by Bentleysb** [comment] 2021-03-08 20:59
For this task it sounds like the next step is to use a standardization library to remove the standardization cases from the check. Once that is done we can reevaluate if a fix suggestion is possible.

**Comment by vladlemberg** [comment] 2021-03-08 21:23
that sound good to me. should we include std lib as utility class in atlas-checks or stand alone project under osm lab ?

**Comment by Bentleysb** [comment] 2021-03-08 22:13
I don't think we need a stand alone project. It could be made part of the Atlas repo, but I think it would be fine in Altas Checks. It would be worth checking if there are any existing libraries that we could consider adding to the project that would serve this purpose.

**Comment by herriotto** [comment] 2021-08-18 17:19
@vladlemberg May I get access to the 1000m challenge you posted above? Im running through some of these in Venezuela and Uruguay, and noticing alot of what you mention above: address points in airports, shopping centre's, Universities.. They are also making up a large % of total Atlas checks in a given market. In VE this check is 25% of all checks, while in Uruguay it is more than 50% of total checks. If there was an option to expand the 100m radius, It would be well worth processing a sample of 500m and 1000m challenges to see what the fix rate was. Thanks

**Closed** 2022-07-07 18:18 UTC
